[tool.poetry]
name = "essensliste"
version = "0.1.0"
description = ""
authors = ["Andy <andy@freilandkiwis.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
